### ISSUE TITLE
Pass data to workers to introspect their retry count

### ISSUE THREAD

**Issue by benbuckman** [Shyp/rickover#5]
It would be nice, if a job is retried, for the worker code to be able to know how many times it has been retried.
Perhaps the payload passed to the worker can have a `meta` property with (for example) `try_count`, and any other context that the worker might find useful.

**Comment by kevinburke** [comment]
In theory you could compare the `attempts` value for the job to the `attempts` value set on the QueuedJob and back out the number of tries. Otherwise you'd need to run a migration to store failed_attempts or something on the queued_jobs table.

**Comment by caseycrites** [comment]
@benbuckman Isn't the current `attempts` key passed as part of the payload to the downstream worker sufficient? If it's >1, then it's a retry.

I can see another discussion here about adding metadata about the job configuration itself, so that you know that you can use the `attempts` key to know this job has been tried 2 times AND some other key to tell you it's configured to try 5 times, which would allow you to take some custom action when you know this is the last time the job will be run.

**Comment by benbuckman** [comment]
Yes, it does seem like that would be sufficient.
I don't remember the original context for this request ... I'll close this ticket.
Thanks!
